### PR TITLE
Add 🚀🦀 rocketcrab support

### PR DESCRIPTION
**Pull request by tannerkrewson**
Hey folks! Love the game! Myself and a few other mobile web party game developers have been working on [rocketcrab](https://rocketcrab.com/), and we'd love to add Fishbowl! Many games can be added to 🚀🦀 without any changes, but Fishbowl needed a few changes to work. Here's what I've added in this PR:

- The rocketcrab server [needs a way](https://github.com/tannerkrewson/rocketcrab#step-1-ensuring-compatability) to create a lobby in supported games. So, I've added a `newGame` endpoint that generates an empty lobby, and returns its game code.
- This caused an issue where no player would be host. This is fixed by automatically making the first player that joins the host if there is not already a host.
- As a bonus, I've added code that will automatically set a player's username if a `name=John` param is added to the URL, and also hides the share section if a `hideshare=true` param is added to the URL. These two features will make a big difference for rocketcrab players! 🎉 

Let me know if you have any concerns, or you notice any mistakes. Also, [join our discord](https://discord.gg/MvYRVCP) if you'd like; we'd love to hear from you! 😄

### CODE REVIEW

**Comment by avimoondra** [comment]
@tannerkrewson I introduced some merge conflicts when merging https://github.com/avimoondra/fishbowl/pull/89, I'll update this branch tmrw and test! 

Thanks again for putting up the PR, looking forward to seeing it on 🚀 🦀

**Comment by avimoondra** [comment]
[Add Rocket Crab support](https://trello.com/c/VzdFNAdZ/112-add-rocket-crab-support)

**Comment by tannerkrewson** [comment]
closed in favor of #110

**Comment by avimoondra** [comment]
[Add Rocket Crab support](https://trello.com/c/VzdFNAdZ/112-add-rocket-crab-support)

**Pull request closed without merging**
